#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Find the best model (by avg coverage_end, then shortest path_length_end) for each ablation study name,
then launch benchmark jobs for each.

Expected CSV format (generated by z_ablation_study_postprocess.py):
    - ablation_study_name: Name of the ablation study
    - sweep_id: W&B sweep ID
    - epoch: Model epoch number
    - coverage_end: Coverage at end of episode
    - path_length_end: Path length at end of episode
    - map: Map identifier
    - run_number: Run number
    - Other columns: timestamp, model, seed, path_length_90_pct, etc.

The script will:
1. Group data by (ablation_study_name, sweep_id, epoch)
2. Calculate average coverage_end across all maps for each group
3. Find the epoch with highest average coverage_end for each ablation_study_name
4. If multiple epochs have the same max coverage, select the one with shortest path_length_end
5. Launch benchmark jobs for each best model found
"""
from __future__ import annotations

import pandas as pd
import subprocess
import sys
from pathlib import Path
from typing import Dict, Tuple

# Configuration
CSV_FILE = "misc/logs/benchmark_results/ablation_studies_evaluation_files.csv"
BENCHMARK_SCRIPT = "z_start_benchmark_cluster.py"


def load_ablation_data(csv_path: Path) -> pd.DataFrame:
    """Load the ablation studies evaluation CSV file."""
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")
    
    df = pd.read_csv(csv_path)
    print(f"✓ Loaded {len(df)} rows from {csv_path.name}")
    return df

def find_best_models(df: pd.DataFrame) -> pd.DataFrame:
    """
    Find the best model for each ablation study name.
    Best model = highest average coverage_end across all maps AND all sweep_ids for that epoch/ablation_study.
    Tiebreaker (when coverage values are close or equal): select the one with shortest path_length_end.
    
    This logic matches vis_for_icaps_paper.py: 
    - Groups by ablation_study_name and epoch only (combining all sweep_ids)
    - Sorts by coverage (descending) then path_length (ascending)
    - After finding best epoch, selects the specific sweep_id with best performance for that epoch
    
    Returns a DataFrame with columns: ablation_study_name, epoch, avg_coverage_end, avg_path_end, sweep_id
    """
    # Convert epoch to numeric if it's not already
    # Handle cases where epoch might be "epoch-X" format
    if df['epoch'].dtype == 'object':
        df['epoch_num'] = df['epoch'].astype(str).str.extract(r'epoch-(\d+)')[0].astype(int)
    else:
        df['epoch_num'] = df['epoch'].astype(int)
    
    # Convert path_length_end to numeric, handling empty strings and non-numeric values
    df['path_length_end'] = pd.to_numeric(df['path_length_end'], errors='coerce')
    
    # Group by ablation_study_name and epoch_num (NOT by sweep_id - combine all sweeps)
    # Calculate mean coverage_end and mean path_length_end across all maps and all sweep_ids for each group
    grouped = df.groupby(['ablation_study_name', 'epoch_num']).agg({
        'coverage_end': 'mean',
        'path_length_end': 'mean',
        'epoch': 'first'
    }).reset_index()
    grouped.rename(columns={
        'coverage_end': 'avg_coverage_end',
        'path_length_end': 'avg_path_end'
    }, inplace=True)
    
    # For each ablation_study_name, find the best epoch
    best_models = []
    for ablation_study in grouped['ablation_study_name'].unique():
        study_data = grouped[grouped['ablation_study_name'] == ablation_study].copy()
        
        # Sort by coverage (descending) then path_length (ascending) as tiebreaker
        # This matches the logic in vis_for_icaps_paper.py
        # Handle NaN values in path_length by filling with infinity
        study_data['path_sort_key'] = study_data['avg_path_end'].fillna(float('inf'))
        study_data_sorted = study_data.sort_values(['avg_coverage_end', 'path_sort_key'], 
                                                    ascending=[False, True])
        
        # Select the best epoch (first row after sorting)
        best_epoch_row = study_data_sorted.iloc[0]
        best_epoch_num = int(best_epoch_row['epoch_num'])
        
        # Check if there were ties in coverage
        max_coverage = best_epoch_row['avg_coverage_end']
        tied_rows = study_data[study_data['avg_coverage_end'] == max_coverage]
        
        if len(tied_rows) > 1:
            print(f"  ℹ Tiebreaker applied for '{ablation_study}': {len(tied_rows)} epochs with coverage {max_coverage:.4f}")
            print(f"    Selected epoch {best_epoch_num} with path_end={best_epoch_row['avg_path_end']:.2f}")
        
        # Now find the specific sweep_id with the best performance for this epoch
        # Get all data for this ablation study and epoch across all sweep_ids
        epoch_data = df[(df['ablation_study_name'] == ablation_study) & 
                        (df['epoch_num'] == best_epoch_num)].copy()
        
        # Group by sweep_id to find which one performs best for this epoch
        sweep_stats = epoch_data.groupby('sweep_id').agg({
            'coverage_end': 'mean',
            'path_length_end': 'mean'
        }).reset_index()
        
        # Sort to find best sweep_id (same logic: max coverage, then min path length)
        sweep_stats['path_sort_key'] = sweep_stats['path_length_end'].fillna(float('inf'))
        sweep_stats_sorted = sweep_stats.sort_values(['coverage_end', 'path_sort_key'], 
                                                      ascending=[False, True])
        best_sweep_id = sweep_stats_sorted.iloc[0]['sweep_id']
        
        # Create the result row
        result_row = {
            'ablation_study_name': ablation_study,
            'sweep_id': best_sweep_id,
            'epoch': best_epoch_num,
            'epoch_name': best_epoch_row['epoch'],
            'avg_coverage_end': best_epoch_row['avg_coverage_end'],
            'avg_path_end': best_epoch_row['avg_path_end']
        }
        
        best_models.append(result_row)
    
    # Create final dataframe
    best_models_df = pd.DataFrame(best_models).reset_index(drop=True)
    
    # Sort by ablation_study_name for better readability
    best_models_df = best_models_df.sort_values('ablation_study_name').reset_index(drop=True)
    
    return best_models_df
    
    # Create final dataframe
    best_models_df = pd.DataFrame(best_models).reset_index(drop=True)
    
    # Sort by ablation_study_name for better readability
    best_models_df = best_models_df.sort_values('ablation_study_name').reset_index(drop=True)
    
    return best_models_df


def print_best_models(best_models: pd.DataFrame) -> None:
    """Print the best models in a formatted way."""
    print("\n" + "=" * 100)
    print("BEST MODELS FOR EACH ABLATION STUDY")
    print("=" * 100)
    print(f"{'Ablation Study Name':<50} {'Sweep ID':<12} {'Epoch':<8} {'Avg Coverage':<14} {'Avg Path End'}")
    print("-" * 100)
    
    for _, row in best_models.iterrows():
        path_end_str = f"{row['avg_path_end']:.2f}" if pd.notna(row['avg_path_end']) else "N/A"
        print(f"{row['ablation_study_name']:<50} {row['sweep_id']:<12} {row['epoch']:<8.0f} {row['avg_coverage_end']:<14.4f} {path_end_str}")
    
    print("=" * 100 + "\n")


def start_benchmark_job(sweep_id: str, epoch: int, ablation_study_name: str) -> bool:
    """
    Start a benchmark job for the given sweep_id and epoch.
    
    Returns True if successful, False otherwise.
    """
    try:
        # Modify the benchmark script to use this sweep_id and epoch
        # We'll use command line arguments instead of modifying the file
        cmd = [
            sys.executable,
            BENCHMARK_SCRIPT,
            "--sweep-id", sweep_id,
            # Note: The script uses constrained_model_number, which corresponds to epoch
            # We'll need to pass this, but the script needs to be modified to accept it via CLI
        ]
        
        print(f"Starting benchmark for {ablation_study_name}...")
        print(f"  Sweep ID: {sweep_id}")
        print(f"  Epoch (Model Number): {epoch}")
        
        # For now, we'll use a simpler approach: modify the script directly
        # Or we can just print the command that should be run
        print(f"  Command: python {BENCHMARK_SCRIPT} --sweep-id {sweep_id}")
        print(f"  Note: Set constrained_model_number = {int(epoch)} in {BENCHMARK_SCRIPT}")
        print()
        
        # Uncomment to actually run:
        # result = subprocess.run(cmd, capture_output=True, text=True)
        # if result.returncode != 0:
        #     print(f"✗ Failed to start benchmark: {result.stderr}")
        #     return False
        # print(f"✓ Benchmark job started successfully")
        # return True
        
        return True
        
    except Exception as e:
        print(f"✗ Error starting benchmark: {e}")
        return False


def modify_and_run_benchmark(sweep_id: str, epoch: int, ablation_study_name: str) -> bool:
    """
    Modify z_start_benchmark_cluster.py with the sweep_id and epoch, then run it.
    """
    benchmark_path = Path(BENCHMARK_SCRIPT)
    if not benchmark_path.exists():
        print(f"✗ Benchmark script not found: {benchmark_path}")
        return False
    
    # Read the current file
    content = benchmark_path.read_text(encoding='utf-8')
    
    # Find and replace the sweep_id and constrained_model_number lines
    lines = content.split('\n')
    modified_lines = []
    
    for line in lines:
        if line.strip().startswith('sweep_id = '):
            # Preserve the comment if it exists
            if '#' in line:
                comment_part = line[line.index('#'):]
                modified_lines.append(f'sweep_id = "{sweep_id}" {comment_part}')
            else:
                modified_lines.append(f'sweep_id = "{sweep_id}"')
        elif line.strip().startswith('constrained_model_number = '):
            # Preserve the comment if it exists
            if '#' in line:
                comment_part = line[line.index('#'):]
                modified_lines.append(f'constrained_model_number = {int(epoch)}  {comment_part}')
            else:
                modified_lines.append(f'constrained_model_number = {int(epoch)}')
        else:
            modified_lines.append(line)
    
    # Write back the modified content
    modified_content = '\n'.join(modified_lines)
    benchmark_path.write_text(modified_content, encoding='utf-8')
    
    print(f"✓ Modified {BENCHMARK_SCRIPT}:")
    print(f"    sweep_id = \"{sweep_id}\"")
    print(f"    constrained_model_number = {int(epoch)}")
    print(f"    Ablation Study: {ablation_study_name}")
    print()
    
    # Run the benchmark script
    try:
        print(f"⏳ Starting benchmark job...")
        result = subprocess.run([sys.executable, str(benchmark_path)], 
                              capture_output=True, text=True, encoding='utf-8')
        
        if result.returncode != 0:
            print(f"✗ Benchmark script failed:")
            print(result.stderr)
            return False
        
        print(result.stdout)
        print(f"✓ Benchmark job submitted successfully\n")
        print("-" * 80 + "\n")
        return True
        
    except Exception as e:
        print(f"✗ Error running benchmark script: {e}")
        return False


def main():
    """Main execution function."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Find best models for each ablation study and launch benchmarks"
    )
    parser.add_argument(
        "--csv-file",
        type=Path,
        default=Path(CSV_FILE),
        help=f"Path to ablation studies CSV file (default: {CSV_FILE})"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without actually starting benchmark jobs"
    )
    parser.add_argument(
        "--auto",
        action="store_true",
        help="Automatically start all benchmark jobs without prompting"
    )
    
    args = parser.parse_args()
    csv_path = args.csv_file
    
    # Check if CSV exists
    if not csv_path.exists():
        print(f"✗ CSV file not found: {csv_path}")
        print(f"  Please ensure the CSV file exists.")
        print(f"  You can generate it by running: python z_ablation_study_postprocess.py")
        sys.exit(1)
    
    # Load data
    df = load_ablation_data(csv_path)
    
    # Check required columns
    required_columns = ['ablation_study_name', 'sweep_id', 'epoch', 'coverage_end']
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        print(f"✗ Missing required columns in CSV: {', '.join(missing_columns)}")
        print(f"  Available columns: {', '.join(df.columns)}")
        sys.exit(1)
    
    # Find best models
    best_models = find_best_models(df)
    
    # Print results
    print_best_models(best_models)
    
    # Check if running in dry-run mode
    if args.dry_run:
        print("DRY RUN MODE - No benchmark jobs will be started")
        print("\nThe following commands would be executed:\n")
        for idx, row in best_models.iterrows():
            sweep_id = row['sweep_id']
            epoch = int(row['epoch'])
            ablation_study_name = row['ablation_study_name']
            print(f"[{idx + 1}/{len(best_models)}] {ablation_study_name}")
            print(f"  python {BENCHMARK_SCRIPT} --sweep-id {sweep_id}")
            print(f"  (with constrained_model_number = {epoch})")
            print()
        sys.exit(0)
    
    # Ask user if they want to start benchmark jobs (unless --auto flag is set)
    if not args.auto:
        print(f"Found {len(best_models)} best models.")
        response = input("Do you want to start benchmark jobs for all best models? (yes/no): ").strip().lower()
        
        if response not in ['yes', 'y']:
            print("Benchmark jobs not started. Exiting.")
            sys.exit(0)
    else:
        print(f"AUTO MODE: Starting benchmark jobs for {len(best_models)} best models...")
    
    # Start benchmark jobs for each best model
    print("\n" + "=" * 80)
    print("STARTING BENCHMARK JOBS")
    print("=" * 80 + "\n")
    
    success_count = 0
    for idx, row in best_models.iterrows():
        sweep_id = row['sweep_id']
        epoch = int(row['epoch'])
        ablation_study_name = row['ablation_study_name']
        
        print(f"[{idx + 1}/{len(best_models)}] Processing: {ablation_study_name}")
        
        if modify_and_run_benchmark(sweep_id, epoch, ablation_study_name):
            success_count += 1
    
    print("=" * 80)
    print(f"✓ Successfully started {success_count}/{len(best_models)} benchmark jobs")
    print("=" * 80)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n✗ Interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
